version: '3.9'
services:
  redis:
    container_name: redis_container
    image: redis:alpine
    restart: always
    command: redis-server --loglevel warning
    volumes:
      - ./docker-volumes/cache:/data
    ports:
      - "6379:6379"
  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    volumes:
      - ./docker-volumes/mongodb:/data/db
    ports:
      - "27017:27017"
  mysql:
    container_name: mysql_container
    image: mysql:latest
    restart: always
    volumes:
      - ./docker-volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: api
      MYSQL_DATABASE: jobber_auth
      MYSQL_USER: jobber
      MYSQL_PASSWORD: api
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
  postgres:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: jobber
      POSTGRES_PASSWORD: api
      POSTGRES_DB: jobber_reviews 
    ports:
      - "5432:5432"
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3.13-rc-management-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: jobber
      RABBITMQ_DEFAULT_PASS: api      

